name: Deploy and Update Sitemap

on:
  workflow_call: # Makes this workflow reusable
    inputs:
      site_url:
        description: "The base URL of the website"
        required: true
        type: string
      publish_branch:
        description: "The branch to publish GitHub Pages"
        required: false
        default: gh-pages
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Lint JavaScript
        run: npm run lint

      - name: Generate sitemap
        run: node generate-sitemap.mjs

      - name: Check Sitemap Generation
        run: |
          if [ ! -f ./sitemap.xml ]; then
            echo "Sitemap generation failed!" && exit 1
          fi

      - name: Validate Sitemap
        run: |
          if ! grep -q "<url>" ./sitemap.xml; then
            echo "Sitemap does not contain valid URLs!" && exit 1
          fi

      - name: Minify JavaScript
        run: npm run build:js

      - name: Minify CSS
        run: npm run build:css

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: ${{ inputs.publish_branch }}

      - name: Validate HTML
        run: |
          curl -s -H "Content-Type: text/html; charset=utf-8" \
          --data-binary @./index.html \
          https://validator.w3.org/nu/?out=text \
          -o ./html-validation-report.txt
          if grep -q "Error" ./html-validation-report.txt; then
            echo "HTML validation errors found! Check html-validation-report.txt for details."
          fi
          echo "HTML validation completed."